### ISSUE TITLE
how to use DeepDTA-Pytorch

### ISSUE THREAD

**Issue by Golden-proteogenomics** [KSUN63/DeepDTA-Pytorch#2]
hello, 

I find it intriguing to delve into DeepDTA using PyTorch, which is a commendable achievement. However, I can not use demo data or file to run notebook, could you can give a sample data such as 'our_data.csv' , 'test-result*.txt' and other for completing notebook?

**Comment by KSUN63** [comment]
Sorry for my horrible oversight! Sure I can include some examples
